# Generated by Django 3.0.7 on 2020-06-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_remove_stockdata_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockData_sam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='stockData',
            new_name='stockData_lg',
        ),
    ]
