# Generated by Django 3.0.7 on 2020-06-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_stockdata_kakao_stockdata_naver_stockdata_nc'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
        ),
    ]
